import esbuild from "esbuild";
import process from "process";
// Use Node's built-in modules list to avoid JSON import assertions incompatibility
import { builtinModules as nodeBuiltinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
    "@lezer/lr",
    ...nodeBuiltinModules
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	// Minify production builds. The unminified bundle exceeds the size/AST
	// limits of several static-analysis and malware scanners, which then skip
	// the file instead of reporting a result.
	minify: prod,
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
