name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Ensure gh-pages branch exists
        run: |
          if ! git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "init gh-pages"
            git push origin gh-pages
            git checkout -
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
        working-directory: taskchute-docs

      - run: npm run build
        working-directory: taskchute-docs

      - name: Deploy
        run: npx docusaurus deploy
        working-directory: taskchute-docs
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
