name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
        working-directory: taskchute-docs

      - run: npm run build
        working-directory: taskchute-docs

      - name: Deploy
        run: npx docusaurus deploy
        working-directory: taskchute-docs
        env:
          GIT_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
